### ISSUE TITLE
Build failure on OS X

### ISSUE THREAD

**Issue by woodscn** [manufactured-solutions/MASA#22]
This is somewhat new; it used to build just fine. 

After installing automake & libtool (brew install automake libtool), ./bootstrap runs fine. ./configure (run with no arguments) fails with the error:

    checking whether we are cross compiling... configure: error: in `/Users/~~~~~/MASA':
    configure: error: cannot run C compiled programs.
    If you meant to cross compile, use `--host'.
    See `config.log' for more details

The relevant part of config.log appears to be:

    configure:3851: checking whether we are cross compiling
    configure:3859: clang -o conftest -arch x86_64 -mmacosx-version-min=10.6  -undefined dynamic_lookup -bundle -arch x86_64 conftest.c  >&5
    configure:3863: $? = 0
    configure:3870: ./conftest
    ./configure: line 3872: ./conftest: cannot execute binary file
    configure:3874: $? = 126
    configure:3881: error: in `/Users/~~~~~/MASA':
    configure:3883: error: cannot run C compiled programs.
    If you meant to cross compile, use `--host'.
    See `config.log' for more details

Any ideas what's going on, or how to go about debugging it? 

On a related note, I can't find anywhere to access the documentation without compiling the package. It would be nice if a .pdf were included in the repository or on the website.

**Comment by nicholasmalaya** [comment]
Offhand, I do not know what might be causing that error, but then again, I'm not a mac guy. @dmcdougall @pbauman, any ideas, off-the-cuff? I can take a pass at reproducing this error over the weekend, when I can steal my wife's apple computer. 

I'm attaching the masa documentation to you separately in an email (github does not support pdfs), but I think this is a good idea: I'll start a ticket to add the latest documentation to the webspace.

**Comment by nicholasmalaya** [comment]
Karl just provided a recommendation: "Looks like he’s using clang directly and it can’t execute an executable. c compiler may not be cooperating in his environment."

If you have a working gcc, it is probably worth trying ./configure CC=gcc CXX=g++, FC=gfortran, etc.

**Comment by koomie** [comment]
Just to expand a bit, in addition to a working C/C++ compiler, your going to need a working Fortran compiler as MASA will build Fortran interfaces as well. This means that even if clang is able to execute locally, you will need more than clang to complete the build.

We've tended to always test with gcc on OS X, and since you need fortran anyway, I'd probably recommend pulling a recent gcc install from brew, macports, etc. I just quickly ran the compile and companion regression tests using gcc 4.8.3 from macports on OS X Yosemite and it went through ok.

**Comment by pbauman** [comment]
We should probably have a disable fortran configure option.

**Comment by koomie** [comment]
Agreed. That would be pretty straightforward to add.

ps, Fortran called to say it desparately misses you @pbauman .......

**Comment by pbauman** [comment]
> On Feb 27, 2015, at 6:40 PM, koomie <notifications@github.com> wrote:

> ps, Fortran called to say it desparately misses you @pbauman .......

Yeah, and it gets sent straight to voicemail.

**Comment by woodscn** [comment]
I'd rather not install a whole new build system just for this...

Fortran isn't a problem, and I have a clang-compatible gfortran installed. I'd rather figure out what's causing the crash. I'll check compilation of a test .c file, just to be sure, but I don't know enough about autoconf to know how to check that file specifically.

**Comment by dmcdougall** [comment]
I just tried to configure with `clang` and everything went through fine (I'm using `gfortran` from MacPorts):

```
Package version................. : masa-0.44.0

C++ compiler.................... : clang++
C++ compiler flags.............. : -O0 -fno-unsafe-math-optimizations -Dgnu_compiler
C compiler...................... : clang
C compiler flags................ : -O0 -fno-unsafe-math-optimizations -Dgnu_compiler
Fortran compiler................ : gfortran-mp-4.9
Fortran compiler flags.......... : -O0 -fno-unsafe-math-optimizations -Dgnu_compiler
Install dir..................... : /Users/damon/MASA
Build user...................... : damon
Build host...................... : quagmire.local
Configure date.................. : 2015-04-20 12:51
Build architecture.............. : x86_64-apple-darwin14.3.0
Source control revision......... : 67ace0c

Optional Features:
   Enable gcov code coverage.... : no
   Enable absolute error tests.. : no
   Enable all warnings.......... : no
   Enable python interfaces..... : no
```

**Comment by dmcdougall** [comment]
@woodscn What version of `clang` are you using?

```
$ clang --version
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

$ clang++ --version
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

**Comment by woodscn** [comment]
Same as you, it looks like. I'm including the gfortran version and my environment variables for good measure. The system is set up for building SciPy from source, based on their build page: http://www.scipy.org/scipylib/building/macosx.html

$ clang --version
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

$ clang++ --version
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

$ gfortran --version
GNU Fortran (GCC) 4.2.3
Copyright (C) 2007 Free Software Foundation, Inc.

export CC=clang
export CXX=clang++
export CFLAGS="-arch x86_64 -mmacosx-version-min=10.6"
export CXXFLAGS="-stdlib=libstdc++ -mmacosx-version-min=10.6 "$CFLAGS
export FFLAGS="-arch x86_64 -ff2c"
export LDFLAGS="-WALL -undefined dynamic_lookup -bundle -arch x86_64"

**Comment by dmcdougall** [comment]
I can recreate the error if I use your environment variables.  Thanks for that information.

**Comment by dmcdougall** [comment]
@woodscn For me, the `-bundle` option in `LDFLAGS` is causing the problem.  Try removing that and rebuilding.  It's a workaround for now, but I imagine autotools doesn't support all the OS X specific linker flags.

**Comment by dmcdougall** [comment]
@woodscn Actually, this is nothing to do with autotools, the `-bundle` flag will not produce an executable format:

```
$ cat helloworld.c
#include <stdio.h>

int main(void) {
  printf("Hello world\n");
  return 0;
}

$ clang -o helloworld -arch x86_64 -mmacosx-version-min=10.6  -Wall -undefined dynamic_lookup -bundle -arch x86_64 helloworld.c

$ ./helloworld
-bash: ./helloworld: cannot execute binary file: Exec format error
```

P.S. `-WALL` is not a valid linker flag, try `-Wall` instead

**Comment by woodscn** [comment]
This is odd, because the exact same code compiles and runs fine on my machine in a new terminal window. If I clear my environment variables and run the flags from the command line (as in your example), I get the error.

N

**Comment by dmcdougall** [comment]
> This is odd, because the exact same code compiles and runs fine on my machine in a new terminal window.

Why is that odd?  If you're not explicitly passing the flags to the compiler, then this is not odd at all.  Invoking `clang` (or any compiler for that matter) will not suck up values from environment variables.

To clarify, you need to do one of either

```
$ clang -o helloworld -bundle helloworld.c
```

or

```
$ export LDFLAGS="-bundle"
$ clang -o helloworld $LDFLAGS helloworld.c
```

to recreate the problem.

If you're saying you can recreate the problem with the first, then we're good (the second is equivalent to the first).  All that was happening was that a flag was being passed to the linker that forced the creation of bundles rather than executables.  As a result, all of the resulting `configure` tests don't produce executables and therefore fail.

> If I clear my environment variables and run the flags from the command line (as in your example), I get the error.

Yep.  The compiler flags and the environment variables are totally independent (in the `helloworld` example above).  Environment variables are only sucked up by `autotools`, not the compiiler itself.  `autotools` passes the environment variables directly to the compiler.

**Comment by woodscn** [comment]
All right, my mistake was assuming that the compiler paid attention to environment variables. Thanks for the help!


> On Apr 20, 2015, at 4:13 PM, Damon McDougall <notifications@github.com> wrote:
> 
> This is odd, because the exact same code compiles and runs fine on my machine in a new terminal window.
> 
> Why is that odd? If you're not explicitly passing the flags to the compiler, then this is not odd at all. Invoking clang (or any compiler for that matter) will not suck up values from environment variables.
> 
> To clarify, you need to do one of either
> 
> $ clang -o helloworld -bundle helloworld.c
> or
> 
> $ export LDFLAGS="-bundle"
> $ clang -o helloworld $LDFLAGS helloworld.c
> to recreate the problem.
> 
To nitpick, this second example does not recreate the problem, for the reasons you’ve already explained.

**Comment by dmcdougall** [comment]
>> $ export LDFLAGS="-bundle"
>> $ clang -o helloworld $LDFLAGS helloworld.c
>
> To nitpick, this second example does not recreate the problem, for the reasons you’ve already explained.

This example __does__ recreate the problem for __exactly__ the reasons I explained.  In this example I passed the flags to the compiler explicitly.  It doesn't matter that they're held in an environment variable.

What I explained is that compilers will not suck up environment variables when not passed explicitly.

```
$ cat helloworld.c
#include <stdio.h>

int main (void) {
  printf("Hello world\n");
  return 0;
}

$ echo $LDFLAGS

$ export LDFLAGS="-bundle"
$ clang -o helloworld $LDFLAGS helloworld.c
$ ./helloworld
-bash: ./helloworld: cannot execute binary file: Exec format error
$ clang -o helloworld helloworld.c
$ ./helloworld
Hello world
```

**Comment by woodscn** [comment]
Ah. Somehow I missed seeing the $LDFLAGS there. Sorry about that.

**Comment by dmcdougall** [comment]
> Ah. Somehow I missed seeing the $LDFLAGS there. Sorry about that.

No worries.

It looks like this issue is resolved, so I'm going to close the ticket.  Thanks for reporting the issue about the documentation.  I'll open a separate ticket for that.
