### ISSUE TITLE
Permit disabling Fortran Interfaces 

### ISSUE THREAD

**Issue by nicholasmalaya** [manufactured-solutions/MASA#24]
Let's leave them on by default (it is the language of scientific computing!) but permit disabling construction by passing a flag, such as --disable-fortan-interfaces

This may help encourage more general MASA use.

**Comment by RhysU** [comment]
Should be possible to autodetect without needing a flag. Look at the
Autoconf. Could take a stab early next week if  you like.

- Rhys

**Comment by koomie** [comment]
While that would be trivial, I would be in favor of asking the user to opt out if they don’t want it. That’s better in my mind to avoid building/installing in an environment that may need some extra flags set to define FC (e.g. building support for vendor compilers) and having things seemingly go ok, only to have a user find out later that their fortran symbols are missing.

Perhaps a compromise would be to put some extra language around the Fortran test to notify the user that there is a “—disable-fortran” option if the autoconf fortran test fails?

**Comment by nicholasmalaya** [comment]
Merged in #25
