### ISSUE TITLE
Prep for 0.50.0 release

### ISSUE THREAD

**Issue by nicholasmalaya** [manufactured-solutions/MASA#41]
I'm planning on pushing out at 0.50 release this calendar year. Certainly will not be in Nov. 

If anyone is working on a specific bug or feature they would like included let me know. I'll update ticket as I move forward.

**Comment by roystgnr** [comment]
I think #43 was the last fix we needed; we should be good to release now.

I'll update the CHANGELOG with that fix.

**Comment by nicholasmalaya** [comment]
Thank you @roystgnr. Alright, I think we are all prepped. I'm going to set this guy up for release.

**Comment by nicholasmalaya** [comment]
https://github.com/manufactured-solutions/MASA/releases/tag/0.50.0

Thanks, all.
