### ISSUE TITLE
Problems running on OSX

### ISSUE THREAD

**Issue by jrood-nrel** [manufactured-solutions/MASA#49]
I can build and run MASA fine in my application on Linux with GCC 5.2.0. If I use the same process and build MASA on OSX using GCC 5.4.0 or 7.2.0, it builds fine without issues. However, when I run my application, I can verify that I am calling `masa_init`, but I get this seemingly if and only if I'm on OSX:

```
Initializing MMS
MASA FATAL ERROR:: No initialized Manufactured Solution!
Have you called masa_init?
MASA:: ABORTING
```

Has anyone else experienced this on OSX to know if I'm doing something wrong?

**Comment by nicholasmalaya** [comment]
Hi @jrood-nrel,

Can you show the pertinent MASA calls? E.g. how are you invoking masa_init? I don't have access to an OSX box but we would like to support it. @dmcdougall or @trevilo might be able to try reproducing your error.

**Comment by jrood-nrel** [comment]
Sure, so we have this code and I added the line to output the solution name to verify the init is called:
```
  if (!mms_initialized){
    if (verbose && ParallelDescriptor::IOProcessor()) {
      std::cout << "Initializing MMS" << std::endl;
    }
#ifdef USE_MASA
    masa_init("mms", masa_solution_name.c_str());
    std::cout << masa_solution_name.c_str() << std::endl;
#endif
    mms_initialized = true;
  }
```

**Comment by roystgnr** [comment]
Is this one of those cases where OSX doesn't bother to run the constructors for global objects?  I.e. are you statically linking?  masa_init() uses a static global under the hood, though I didn't actually think we were dependent on its constructor being run automatically, so my guess here is probably a red herring...

See https://github.com/libqueso/queso/pull/508 for some discussion from another project.

**Comment by jrood-nrel** [comment]
So I'm guessing OSX is defaulting to shared linking:
```
USE_MASA   = TRUE
ifeq ($(USE_MASA), TRUE)
INCLUDE_LOCATIONS += ${MASA_HOME}/include ${MASA_HOME}/lib
LIBRARY_LOCATIONS += ${MASA_HOME}/lib
LIBRARIES += -Wl,-rpath,${MASA_HOME}/lib -lmasa -lfmasa
DEFINES += -DUSE_MASA -DDO_PROBLEM_POST_TIMESTEP -DDO_PROBLEM_POST_INIT
endif
```
and
```
374B Oct 18 13:21 .
238B Oct 18 13:21 ..
3.8M Oct 18 13:21 libfmasa-0.51.dylib
19B  Oct 18 13:21 libfmasa.dylib -> libfmasa-0.51.dylib
1.0K Oct 18 13:21 libfmasa.la
3.8M Oct 18 13:21 libmasa-0.51.dylib
18B  Oct 18 13:21 libmasa.dylib -> libmasa-0.51.dylib
1.0K Oct 18 13:21 libmasa.la
6.8K Oct 18 13:21 masa.mod
102B Oct 18 13:21 pkgconfig
102B Oct 18 13:21 python2.7
```

**Comment by roystgnr** [comment]
Yeah, it is.  My constructor guess can't be the problem, then.

I hate debugging-via-email, but I don't have an OSX box to try and replicate this with myself.  Could you get into a "-O0 -g" build with gdb and see what's going on?  In particular I'd break in the masa_init() call and see what the address is of the MasterMS that's getting initialized (IIRC it should be the same as ```&masa_master_double```, since you're using the non-templated masa_init), then break where the error occurs and see which MasterMS you're in.  The stack trace might also help.

**Comment by jrood-nrel** [comment]
So I came here to post this issue because I am still seeing it and didn't realize I had already seen it and posted an issue about it. If I use GCC 9.1.0 on OSX, it seems to work now, but GCC 7.4.0 still exhibits this problem.

**Comment by roystgnr** [comment]
Still suspicious.  If this was a GCC bug that got deliberately fixed, they're usually pretty good about backporting fixes.  GCC 7.4 isn't *that* old, and it's still a supported release.
